name: Lint & Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. チェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # 3. pnpm セットアップ
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 4. 依存関係インストール
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. ESLint + Prettier チェック
      - name: Run lint & prettier check
        run: pnpm check
